language: generic

before_install:
  - export SWIFT_VERSION=$(<.swift-version)
  - export SWIFT_DOCKER_IMAGE=swift:${SWIFT_VERSION}-bionic

stages:
- name: test
  if: tag IS NOT present

jobs:
  include:

    - stage: test
      name: Unit Tests
      os: linux
      dist: bionic
      services: docker
      script:
        - docker pull ${SWIFT_DOCKER_IMAGE}
        - args="swift build --enable-test-discovery -c debug
            && swift build --enable-test-discovery -c release
            && swift test --enable-test-discovery -c debug --sanitize=thread"
        - docker run --rm -v $(pwd):/app -v ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent --workdir /app ${SWIFT_DOCKER_IMAGE} bash -c "${args}"

    - stage: test
      name: Unit Tests
      os: osx
      osx_image: xcode11.4
      before_script:
        - gem install bundler
        - bundle install
        - brew update
        - brew tap vapor/tap && brew install vapor
        - brew outdated swiftlint || brew upgrade swiftlint
      script:
        - swift --version
        - swift build -c debug
        - swift build -c release
        - swift test -c debug --sanitize=thread --enable-test-discovery
        - swiftlint

notifications:
  email:
    on_success: never
    on_failure: change
